### PR TITLE
Add SBT and script to run app without installing Play2

### PR DESCRIPTION
**Pull request by tobnee**
Probably it is easier to add that jar/script to the app then forcing the users to install play2. Especially for a prototype.

### CODE REVIEW

**Comment by FND** [comment]
Build artifacts like this do not belong into a _source code_ repository IMO.

**Comment by martinei** [comment]
I feel its kind of an edge case. the launcher jar is a bootstraping mechanism.

**Comment by tobnee** [comment]
This is suggested to enable more feedback for this project. Which would be a benefit from my point of view. Because it helps getting things started without having to worry about tools which most developers don't have on their machines.

I agree that artifacts like lib dependencies don't belong in git because there are obvious reasons against that approach. I see no disadvantage in doing things simpler, without adding something bad (besides 800k of repo space ;))

**Comment by FND** [comment]
My preferred approach would be to provide a distribution (e.g. a simple ZIP file) which includes the application source as well as dependencies / build artifacts. I imagine that should be a trivial script to write - but I'm entirely ignorant, of course.

**Comment by martinei** [comment]
Creating such a distribution is as simple as runnign "play dist" . Does this Project have a CI server to do so?

**Comment by stilkov** [comment]
My preference is to do whatever is idiomatic for the particular kind of project. In a Java project, this would be Maven. If it's SBT in Scala, I'd be fine with that too.

**Comment by martinei** [comment]
The idiomatic way is to leave it as it is. A developer should install play (which includes sbt) and than build via play.
In addition a CI which build a distribution zip to just run the app would be fine.

**Comment by tobnee** [comment]
A distribution makes things easier for testers / ops people _not_ for devs. I have made very good exp. with that approach in projects with sbt/gradle and maven, especially if your can not force people to give feedback :).

Making things easy for devs to collaborate is good and is has nothing to do with being idiomatic. The tool is the same in both approaches (SBT) the only difference is how to get the tool.

Independent of my disagreement I want to add that it is enough to install SBT which will get the dependencies automatically. Basically thats what the code in this pull request does.

**Comment by stilkov** [comment]
But having a .zip-style distribution built from a CI server would satisfy testers' and ops people's needs, too. Right?

**Comment by martinei** [comment]
How about a bash/ curl to download the launcher jar ?

**Comment by tobnee** [comment]
Yes, it would satisfy testers and ops. But it is no gain to a dev because they do not work with the binary project and if someone likes to change/add/test something the "install xyz" story starts.

**Comment by tobnee** [comment]
@martinei that would work to. Although I don't see the advantage ;)

**Comment by stilkov** [comment]
To take @tobnee's side, I very much appreciate the fact that amazonp "just works" without my having to install anything.

**Comment by FND** [comment]
> Yes, it would satisfy testers and ops. But it is no gain to a dev because they do not work with the binary project

I would think developers would simply run something like `make dependencies` - so yeah, basically what @martinei proposed.

As for the advantage, well, it's cleaner that way? That sounds silly and purist, but there are actual consequences to committing such binary blobs (think, for example, `grep`ing or upgrades of such blobs - that's just annoying bloat in the repo).

Anyway, sorry for derailing this with my nagging...

**Comment by arnelandwehr** [comment]
@tobnee thx for this PR!

@martinei nope there is not any CI-Build yet. Maybe a good task for the next week.

The simplest way for a quick look at the application is perhaps http://roca-prototype-play2.herokuapp.com (i should add the link to the readme). Is there any advantage of the script/jar vs. the deployed version?

**Comment by stilkov** [comment]
I admit I hadn't really noticed the .jar, I though we were talking about a script. I'm strictly against checking in any kind of binary (with the exception of images).

**Comment by tobnee** [comment]
Although I don't get the anti binary thing in this particular instance, I don't care because this wasn't my point anyhow. I adapted the script in the PR to download SBT, which should be fine with anybody, as far as I grok the discussion.

**Comment by tobnee** [comment]
Thanks for the feedback. Script is adapted accordingly.

**Pull request merged**
